export const COUNTRIES = [
  {
    name: 'South Korea',
    originalName: '대한민국',
    languageRegionCode: 'ko-KR',
    countryCode: 'KR',
    phoneCode: '82',
  },
  {
    name: 'Japan',
    originalName: '日本',
    languageRegionCode: 'ja-JP',
    countryCode: 'JP',
    phoneCode: '81',
  },
  {
    name: 'United States',
    originalName: 'United States',
    languageRegionCode: 'en-US',
    countryCode: 'US',
    phoneCode: '1',
  },
  {
    name: 'Canada',
    originalName: 'Canada',
    languageRegionCode: 'en-CA',
    countryCode: 'CA',
    phoneCode: '1',
  },
  {
    name: 'Singapore',
    originalName: 'Singapore',
    languageRegionCode: 'en-SG',
    countryCode: 'SG',
    phoneCode: '65',
  },
  {
    name: 'Malaysia',
    originalName: 'Malaysia',
    languageRegionCode: 'ms-MY',
    countryCode: 'MY',
    phoneCode: '60',
  },
  {
    name: 'Ghana',
    originalName: 'Ghana',
    languageRegionCode: 'en-GH',
    countryCode: 'GH',
    phoneCode: '233',
  },
  {
    name: 'United Kingdom',
    originalName: 'United Kingdom',
    languageRegionCode: 'en-GB',
    countryCode: 'GB',
    phoneCode: '44',
  },
  {
    name: 'Peru',
    originalName: 'Perú',
    languageRegionCode: 'es-PE',
    countryCode: 'PE',
    phoneCode: '51',
  },
  {
    name: 'Germany',
    originalName: 'Deutschland',
    languageRegionCode: 'de-DE',
    countryCode: 'DE',
    phoneCode: '49',
  },
  {
    name: 'Australia',
    originalName: 'Australia',
    languageRegionCode: 'en-AU',
    countryCode: 'AU',
    phoneCode: '61',
  },
  {
    name: 'Vietnam',
    originalName: 'Việt Nam',
    languageRegionCode: 'vi-VN',
    countryCode: 'VN',
    phoneCode: '84',
  },
  {
    name: 'Laos',
    originalName: 'ປະເທດລາວ',
    languageRegionCode: 'lo-LA',
    countryCode: 'LA',
    phoneCode: '856',
  },
  {
    name: 'India',
    originalName: 'भारत',
    languageRegionCode: 'hi-IN',
    countryCode: 'IN',
    phoneCode: '91',
  },
  {
    name: 'Sri Lanka',
    originalName: 'ශ්‍රී ලංකාව',
    languageRegionCode: 'si-LK',
    countryCode: 'LK',
    phoneCode: '94',
  },
  {
    name: 'United Arab Emirates',
    originalName: 'الإمارات العربية المتحدة',
    languageRegionCode: 'ar-AE',
    countryCode: 'AE',
    phoneCode: '971',
  },
];
